# Generated by Django 4.2 on 2024-09-23 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='created_date',
            new_name='create_date',
        ),
    ]
