# Generated by Django 4.2 on 2024-09-30 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0006_question_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='author',
        ),
    ]
